name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  version-check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Package Version
        uses: gilzonme/eazybump@1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-npm:
    needs: version-check-update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - name: Bump Version and Publish
        run: |
          git config --global user.email "gilzon.me@gmail.com"
          git config --global user.name "Gilson Gilbert"
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
